---
- name: Update apt cache
  apt: update_cache=yes

- name: Install Java 17
  apt: name=openjdk-17-jdk state=present

- name: Add Jenkins apt key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Add Jenkins repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins
  apt: name=jenkins state=present update_cache=yes

- name: Start Jenkins
  systemd: name=jenkins state=started enabled=yes

- name: Add jenkins to docker group
  user: name=jenkins groups=docker append=yes

- name: Wait for Jenkins to start
  wait_for: port=8080 delay=15 timeout=60
